kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: autoapprover
  namespace: policies
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
        node-role.kubernetes.io/master: ''
  template:
    metadata:
      labels:
        node-role.kubernetes.io/master: ''
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      serviceAccountName: clusterscaler
      terminationGracePeriodSeconds: 1
      containers:
      - name: signer
        image:  quay.io/cstark/fullocclient
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -c
        args:
        - |
          #!/bin/bash
          set -o errexit
          set -o nounset
          set -o pipefail
          unset KUBECONFIG
          cat <<SCRIPT > /tmp/signer
          #!/bin/bash
          #
          # It will approve any CSR that is not approved yet, and delete any CSR that expired more than 60 seconds
          # ago.
          #
          name=\${1}
          # auto approve
          oc adm certificate approve "\${name}"
          SCRIPT
          chmod u+x /tmp/signer
          exec oc observe csr --maximum-errors=1 --resync-period=1m -- /tmp/signer
