apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cincinatti-operator
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cincinatti-policy-prod
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            apiVersion: cincinnati.openshift.io/v1beta1
            kind: Cincinnati
            metadata:
              name: disconnected-cincinnati
              namespace: cincinnati-operator
            spec:
              graphDataImage: >-
                quay.io/cstark/cincinnati-graph-data-container:latest
              registry: 'bm-cluster-1-hyper.e2e.bos.redhat.com:5000'
              replicas: 1
              repository: ocp4/release
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cincinatti-policy-subscription
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: cincinnati-subscription
                  namespace: cincinnati-operator
                spec:
                  name: cincinnati-operator
                  channel: alpha
                  installPlanApproval: Automatic
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cincinatti-policy-operatorgroup
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: cincinnati-operatorgroup
                  namespace: cincinnati-operator
                spec:
                  targetNamespaces:
                    - cincinnati-operator
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cincinatti-policy-patch-imageconfig
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition: 
                apiVersion: config.openshift.io/v1
                kind: Image
                metadata:
                  annotations: null
                  name: cluster
                spec:
                  additionalTrustedCA:
                    name: trusted-ca
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-cincinatti-operator
  namespace: default
placementRef:
  name: placement-policy-cincinatti-operator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-cincinatti-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-cincinatti-operator
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: env, operator: In, values: ["dev"]}
