apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-kafka-config
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-kafka-config1
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: kafka.strimzi.io/v1beta1
                kind: Kafka
                metadata:
                  name: my-cluster
                spec:
                  kafka:
                    version: 2.6.0
                    replicas: 3
                    listeners:
                      - name: plain
                        port: 9092
                        type: internal
                        tls: false
                      - name: tls
                        port: 9093
                        type: internal
                        tls: true
                    config:
                      offsets.topic.replication.factor: 3
                      transaction.state.log.replication.factor: 3
                      transaction.state.log.min.isr: 2
                      log.message.format.version: '2.6'
                    storage:
                      type: ephemeral
                  zookeeper:
                    replicas: 3
                    storage:
                      type: ephemeral
                  entityOperator:
                    topicOperator: {}
                    userOperator: {}
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-kafka-topics
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: kafka.strimzi.io/v1beta1
                kind: KafkaTopic
                metadata:
                  name: receive-topic
                  labels:
                    strimzi.io/cluster: my-cluster
                spec:
                  config:
                    retention.ms: 7200000
                    segment.bytes: 1073741824
                  partitions: 3
                  replicas: 1
            - complianceType: musthave
              objectDefinition:
                apiVersion: kafka.strimzi.io/v1beta1
                kind: KafkaTopic
                metadata:
                  name: app-topic
                  labels:
                    strimzi.io/cluster: my-cluster
                spec:
                  config:
                    retention.ms: 7200000
                    segment.bytes: 1073741824
                  partitions: 3
                  replicas: 1
            - complianceType: musthave
              objectDefinition:
                apiVersion: kafka.strimzi.io/v1beta1
                kind: KafkaTopic
                metadata:
                  name: infra-topic
                  labels:
                    strimzi.io/cluster: my-cluster
                spec:
                  config:
                    retention.ms: 7200000
                    segment.bytes: 1073741824
                  partitions: 3
                  replicas: 1
            - complianceType: musthave
              objectDefinition:
                apiVersion: kafka.strimzi.io/v1beta1
                kind: KafkaTopic
                metadata:
                  name: audit-topic
                  labels:
                    strimzi.io/cluster: my-cluster
                spec:
                  config:
                    retention.ms: 7200000
                    segment.bytes: 1073741824
                  partitions: 3
                  replicas: 1
          remediationAction: inform
          severity: low
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-kafka-config
  namespace: policies
placementRef:
  name: placement-policy-kafka-config
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-kafka-config
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-kafka-config
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}
