apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-htpasswd-sample
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
          - objectDefinition:
              apiVersion: policy.open-cluster-management.io/v1
              kind: ConfigurationPolicy
              metadata:
                name: policy-secret
              spec:
                remediationAction: inform
                severity: low
                namespaceSelector:
                  exclude:
                    - kube-*
                  include:
                    - default
                object-templates:
                  - complianceType: musthave
                    objectDefinition:
                      apiVersion: v1
                      data:
                        htpasswd: >-
                          dXNlcjE6JDJ5JDA1JFBqUWVqZ1VNMzU5LnJkOE5xQzlweXVHbk9JM3JrVWl4cWh2NDg4enJVNVJvaEhZa2dLWGFhCg==
                      kind: Secret
                      metadata:
                        name: htpass-secret
                        namespace: openshift-config
                      type: Opaque
          - objectDefinition:
              apiVersion: policy.open-cluster-management.io/v1
              kind: ConfigurationPolicy
              metadata:
                name: policy-htpasswd
              spec:
                remediationAction: inform
                severity: low
                namespaceSelector:
                  exclude:
                    - kube-*
                  include:
                    - default
                object-templates:
                  - complianceType: musthave
                    objectDefinition:
                      apiVersion: config.openshift.io/v1
                      kind: OAuth
                      metadata:
                        name: cluster
                      spec:
                        identityProviders:
                          - name: my_identity_provider
                            mappingMethod: claim
                            type: HTPasswd
                            htpasswd:
                              fileData:
                                name: htpass-secret
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-htpasswd-sample
  namespace: gitops
placementRef:
  name: placement-htpasswd-sample
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-htpasswd-sample
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-htpasswd-sample
  namespace: gitops
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
