apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-test-scale
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
      - objectDefinition:
          apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          metadata:
            name: scale-crb
          spec:
            remediationAction: inform # will be overridden by remediationAction in parent policy
            severity: low
            namespaceSelector:
              exclude: ["kube-*"]
              include: ["default"]
            object-templates:
              - complianceType: musthave
                objectDefinition:
                  kind: ClusterRoleBinding
                  apiVersion: rbac.authorization.k8s.io/v1
                  metadata:
                    name: cluster-admin-approver-sa-crb  
                  subjects:
                    - kind: ServiceAccount
                      name: clusterscaler
                      namespace: scale
                  roleRef:
                    kind: ClusterRole
                    name: cluster-admin
                    apiGroup: rbac.authorization.k8s.io
      - objectDefinition:
          apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          metadata:
            name: scale-sa
          spec:
            remediationAction: inform # will be overridden by remediationAction in parent policy
            severity: low
            namespaceSelector:
              exclude: ["kube-*"]
              include: ["default"]
            object-templates:
              - complianceType: musthave
                objectDefinition:
                  kind: ServiceAccount
                  apiVersion: v1
                  metadata:
                    name: clusterscaler
                    namespace: scale
      - objectDefinition:
          apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          metadata:
            name: policy-scale-cm
          spec:
            remediationAction: inform
            severity: low
            namespaceSelector:
              exclude:
                - kube-*
              include:
                - default
            object-templates:
              - complianceType: musthave
                objectDefinition:
                  apiVersion: v1
                  data:
                    script-scale.sh: >
                      export MACHINESETS=$(oc get machineset -n openshift-machine-api -o json | jq '.items[]|.metadata.name' -r )
                      for ms in $MACHINESETS
                      do
                        oc scale  MACHINESET $ms --replicas=0 -n openshift-machine-api
                      done
                  kind: ConfigMap
                  metadata:
                    name: scalemachines-scripts
                    namespace: scale
      - objectDefinition:
          apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          metadata:
            name: scalemachines-job
          spec:
            remediationAction: inform
            severity: low
            namespaceSelector:
              exclude:
                - kube-*
              include:
                - default
            object-templates:
              - complianceType: musthave
                objectDefinition:
                  apiVersion: batch/v1
                  kind: Job
                  metadata:
                    name: scalemachines-job
                    namespace: scale
                  spec:
                    parallelism: 1
                    completions: 1
                    template:
                      metadata:
                        name: scalemachines-job
                        namespace: scale
                      spec:
                        volumes:
                          - name: scalemachines-scripts-volume
                            configMap:
                              name: scalemachines-scripts
                        serviceAccountName: clusterscaler
                        containers:
                          - name: scalemachines-job
                            image: 'quay.io/cstark/fullocclient'
                            volumeMounts:
                              - mountPath: /scalemachines-scripts
                                name: scalemachines-scripts-volume
                            env:
                              - name: HOME
                                value: /tmp
                            command:
                              - /bin/sh
                              - '-c'
                              - |
                                cp /scalemachines-scripts/*.sh /tmp
                                echo "apply 'chmod +x' to /tmp/*.sh"
                                chmod +x /tmp/*.sh
                                echo "execute script sh now"
                                /tmp/script-scale.sh
                        restartPolicy: Never
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-test-scale
  namespace: policies
placementRef:
  name: placement-test-scale
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-test-scale
  kind: Policy
  apiGroup: policy.open-cluster-management.io
  
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-test-scale
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: scale, operator: In, values: ["yes"]}
